import Head from "next/head";
import Header from "../components/landing/Header";
import Main from "../components/landing/Layout";
import { useRouter } from "next/router";
import { useContext, useEffect, useState } from "react";
import UserContext from "../components/context/userContext";
import Footer from "../components/footer";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../firebase";

export default function Index() {
  const router = useRouter();
  const a = useContext(UserContext);

  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <Header/>
    //   <Slider/>
    //   <Content/>
    //   <Feature/>
    //   <Footer/>
    // </div>
    <>
      <Head>
        <title> M J PUBLIC SCHOOL</title>
        <meta name="description" content="Created by akash gandhar" />
        <meta name="viewport" content="width=1024"></meta>
        <link rel="icon" href="/LOGOT.png" />
      </Head>
      <div className="w-fit bg-gradient-to-r from-red-400 via-yellow-400 to-green-500">
        <div className="overflow-hidden top-0 fixed w-full z-[100]">
          <Header />
        </div>
        <div className="xl:h-5 sm:h-20 "></div>
        <Main />
        <Footer />
      </div>
    </>
  );
}
