import Head from 'next/head'
import Header from '../components/landing/Header'
import Main from '../components/landing/Layout'
import Footer from '../components/landing/Footer'
import { useRouter } from 'next/router'
import { useContext } from 'react'
import UserContext from '../components/context/userContext'

export default function Index() {
  const router = useRouter()
  const a = useContext(UserContext)

  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <Header/>
    //   <Slider/>
    //   <Content/>
    //   <Feature/>
    //   <Footer/>
    // </div>
    <>
      <Head>
        <title> M J PUBLIC SCHOOL</title>
        <meta name="description" content="Created by akash gandhar" />
        <meta name="viewport" content="width=1024"></meta>
        <link rel="icon" href="/LOGOT.png" />
      </Head>
      <div className="bg-gradient-to-r from-red-400 via-yellow-400 to-green-500">
        <div className="overflow-hidden top-0 fixed w-full z-50">
          <Header />
        </div>
        <div className="xl:h-5 sm:h-20 "></div>
        <Main />
        <Footer />
      </div>
    </>
  )
}
